---
title: "Figure Code"
format: html
theme: cosmo
page-layout: full
smooth-scroll: true
---

```{css, echo=FALSE}
.subtitle{
  text-align: left;
  margin: 1.25rem 0 0.75rem;
  font-family: var(--bs-font-sans-serif); 
  font-weight: 500;                
  line-height: 1.0;
  font-size: 1.5rem;                       
  color: navy;        
}

```

```{r}
#| include: false
# Load libraries used across figures
library(immunogenetr)
library(tidyverse) 
```

::: {.subtitle}
Figure 1
:::

```{r}
# Adjust table for figure
(HLA_typing_figure_1 <- HLA_typing_1
  # Select the columns for HLA-A, B, DRB1 and DRB3/5/5
  %>% select(patient, A1:A2, B1:B2, DRB1_1:DRB1_2, DRB345_1:DRB345_2)
  # Rename the columns to resemble a clinical LIS
  %>% rename_with(~ str_replace(., "^", "m"))
  %>% rename_with(~ str_replace(., "_", ""))
  %>% rename_with(~ str_replace(., "$", "Cd"))
  # Add a blank value to show how the function handles this entry
  %>% mutate(mA2Cd = if_else(mA2Cd == "A*11:05", "blank", mA2Cd))
  # Remove locus designations
  %>% mutate(across(mA1Cd:mDRB12Cd, ~ str_replace(., "[:alnum:]+\\*", "")))
  %>% mutate(across(mDRB3451Cd:mDRB3452Cd, ~ str_replace(., "DRB", "")))
  # Fix the name of the patient column
  %>% rename(patient = 1)
  # Keep the first three rows
  %>% slice(1:3)
  )

# Use `HLA_columns_to_GLstring` to build GL strings from table
(GL_strings_figure_1 <- HLA_typing_figure_1 
  %>% mutate(
    GL_string = HLA_columns_to_GLstring(.,
      HLA_typing_columns = mA1Cd:mDRB3452Cd,
      prefix_to_remove = "m",
      suffix_to_remove = "Cd"
    )) 
  %>% select(patient, GL_string)
  )
```


```{r}
# Adjust data
HLA_typing_1 <- HLA_typing_1[, -5]
HLA_typing_1 <- HLA_typing_1[, -4]
HLA_typing_1 <- HLA_typing_1 %>% rename_with(~ paste0("m", .x), -1)
HLA_typing_1 <- HLA_typing_1 %>% rename_with(~ paste0(.x, "Cd"), -1)
HLA_typing_1 <- HLA_typing_1[c(1, 2, 6), ]
HLA_typing_1[3, 1] <- 3
HLA_typing_1 <- HLA_typing_1[, 1:9]

names(HLA_typing_1)[6] <- "mDRB3451Cd"
names(HLA_typing_1)[7] <- "mDRB3452Cd"
names(HLA_typing_1)[8] <- "mDRB11Cd"
names(HLA_typing_1)[9] <- "mDRB12Cd"
HLA_typing_1[2, 3] <- "blank"
HLA_typing_1[2, 9] <- "DRB1*03:01"

HLA_typing_1$mA1Cd <- sub("^A\\*", "", HLA_typing_1$mA1Cd)
HLA_typing_1$mA2Cd <- sub("^A\\*", "", HLA_typing_1$mA2Cd)

HLA_typing_1$mB1Cd <- sub("^B\\*", "", HLA_typing_1$mB1Cd)
HLA_typing_1$mB2Cd <- sub("^B\\*", "", HLA_typing_1$mB2Cd)

HLA_typing_1$mDRB3451Cd <- sub("^DRB", "", HLA_typing_1$mDRB3451Cd)
HLA_typing_1$mDRB3452Cd <- sub("^DRB", "", HLA_typing_1$mDRB3452Cd)

HLA_typing_1$mDRB11Cd <- sub("^DRB1\\*", "", HLA_typing_1$mDRB11Cd)
HLA_typing_1$mDRB12Cd <- sub("^DRB1\\*", "", HLA_typing_1$mDRB12Cd)
HLA_typing_1 <- HLA_typing_1 %>% relocate(c(mDRB11Cd, mDRB12Cd), .before = mDRB3451Cd)

print(HLA_typing_1)

# Build GL strings 
GL_strings <- HLA_typing_1 %>%
  mutate(
    GL_string = HLA_columns_to_GLstring(.,
      HLA_typing_columns = mA1Cd:mDRB3452Cd,
      prefix_to_remove = "m",
      suffix_to_remove = "Cd"
    )) %>%
  select(patient, GL_string)

print(GL_strings)
```

::: {.subtitle}
Figure two
:::

```{r}

string <- "HLA-A*02:01+HLA-A*68:01/HLA-A*68:06^HLA-B*07:02+HLA-B*15:01|HLA-B*07:03+HLA-B*15:17"
ambiguity_table <- string %>% GLstring_to_ambiguity_table()
print(ambiguity_table)
filtered_ambiguity_table <- ambiguity_table %>% filter(str_detect(value, "HLA-A"))
print(filtered_ambiguity_table)
new_string <- filtered_ambiguity_table %>% ambiguity_table_to_GLstring()
print(new_string)

```

::: {.subtitle}
Figure three
:::

```{r}
#Adjust data
HLA_typing_LIS[1, 2] <- "24:02novel"
HLA_typing_LIS[2, 3] <- "74:01N"
HLA_typing_LIS[3, 3] <- "32:XX"
HLA_typing_LIS[3, 5] <- "blank"

print(HLA_typing_LIS)

# Run HLA_validate()
HLA_typing_LIS %>%
   mutate(
     across(
       mA1Cd.recipient:mDPB12cd.recipient, 
       HLA_validate)
     )
```


::: {.subtitle}
Figure four
:::

```{r}
GL_string <- "HLA-DQA1*03:03:01/HLA-DQA1*03:03:02/HLA-DQA1*03:03:03"

#To retain duplicates: 
GL_string %>% HLA_truncate (fields = 2)

#To remove duplicates: 
GL_string %>% HLA_truncate (fields = 2, remove_duplicates = TRUE)

```

::: {.subtitle}
Supplemental table 1 links
:::

[R language](https://www.r-project.org)

[cli package](https://cran.r-project.org/web/packages/cli/index.html)

[dplyr package](https://cran.r-project.org/web/packages/dplyr/index.html)

[glue package](https://cran.r-project.org/web/packages/glue/index.html)

[magrittr package](https://cran.r-project.org/web/packages/magrittr/index.html)

[purrr package](https://cran.r-project.org/web/packages/purrr/index.html)

[rlang package](https://cran.r-project.org/web/packages/rlang/index.html)

[stringr package](https://cran.r-project.org/web/packages/stringr/index.html)

[tibble package](https://cran.r-project.org/web/packages/tibble/index.html)

[tidyr package](https://cran.r-project.org/web/packages/tidyr/index.html)

[tidyselect package](https://cran.r-project.org/web/packages/tidyselect/index.html)

[xml2 package](https://cran.r-project.org/web/packages/xml2/index.html)

[testthat package](https://cran.r-project.org/web/packages/testthat/index.html)
