---
title: "Figure Codes"
format: html
theme: cosmo
page-layout: full
smooth-scroll: true
---

```{css, echo=FALSE}
.subtitle{
  text-align: left;
  margin: 1.25rem 0 0.75rem;
  font-family: var(--bs-font-sans-serif); 
  font-weight: 520;                
  line-height: 1.0;
  font-size: 1.5rem;                       
  color: navy;        
}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
options(tidyverse.quiet = TRUE, dplyr.summarise.inform = FALSE)

suppressPackageStartupMessages({
  library(immunogenetr)
  library(dplyr)
  library(stringr)
  library(tibble)
  library(purrr)
})

HLA_typing_1 <- tibble::as_tibble(HLA_typing_1)
HLA_typing_LIS <- tibble::as_tibble(HLA_typing_LIS)

HLA_typing_1_base <- HLA_typing_1
HLA_typing_LIS_base <- HLA_typing_LIS


reset_data <- function(){
  assign("HLA_typing_1", HLA_typing_1_base,  envir = .GlobalEnv)
  assign("HLA_typing_LIS", HLA_typing_LIS_base, envir = .GlobalEnv)
}
```


```{r}
# Load in libraries used across figures
library(immunogenetr)
library(dplyr) # uses functions: %>%, mutate, filter, select, across, rename_with, transmute
library(stringr) # uses function: str_detect
library(tibble) # uses function: tibble
library(purrr) # uses function: map_int

```

::: {.subtitle}
Figure one
:::

```{r}

# Adjust data
HLA_typing_1 <- HLA_typing_1 %>% rename_with(~ paste0("m", .x), -1)
HLA_typing_1 <- HLA_typing_1 %>% rename_with(~ paste0(.x, "Cd"), -1)
HLA_typing_1 <- HLA_typing_1[c(1, 2, 6), ]
HLA_typing_1[3, 1] <- 3
HLA_typing_1[2, 3] <- "A*02:01"
HLA_typing_1[2, 9] <- "DRB3*01:01"
names(HLA_typing_1)[8] <- "mDRB3451Cd"
names(HLA_typing_1)[9] <- "mDRB3452Cd"
print(HLA_typing_1)

# Build GL strings 
GL_strings <- HLA_typing_1 %>%
  mutate(
    GL_string = HLA_columns_to_GLstring(.,
      HLA_typing_columns = mA1Cd:mDRB3452Cd,
      prefix_to_remove = "m",
      suffix_to_remove = "Cd"
    )) %>%
  select(patient, GL_string)

print(GL_strings)
```

::: {.subtitle}
Figure two
:::

```{r}

string <- "HLA-A*02:01+HLA-A*68:01/HLA-A*68:06^HLA-B*07:02+HLA-B*15:01|HLA-B*07:03+HLA-B*15:17"
ambiguity_table <- string %>% GLstring_to_ambiguity_table()
print(ambiguity_table)
filtered_ambiguity_table <- ambiguity_table %>% filter(str_detect(value, "HLA-A"))
print(filtered_ambiguity_table)
new_string <- filtered_ambiguity_table %>% ambiguity_table_to_GLstring()
print(new_string)

```

::: {.subtitle}
Figure three
:::

```{r}
HLA_typing_LIS %>%
   mutate(
     across(
       mA1Cd.recipient:mDPB12cd.recipient, 
       HLA_validate)
     )
```


::: {.subtitle}
Figure four
:::

```{r}
GL_string <- "HLA-DQA1*03:03:01/HLA-DQA1*03:03:02/HLA-DQA1*03:03:03"

#To retain duplicates: 
GL_string %>% HLA_truncate (fields = 2)

#To remove duplicates: 
GL_string %>% HLA_truncate (fields = 2, remove_duplicates = TRUE)

```

::: {.subtitle}
Figure five
:::

```{r, echo = FALSE}
reset_data()
```

```{r}
HLA_typing_1$A1 <- substr(HLA_typing_1$A1, 3, nchar(HLA_typing_1$A1))
HLA_typing_1$A2 <- substr(HLA_typing_1$A2, 3, nchar(HLA_typing_1$A2))
HLA_typing_1$C1 <- substr(HLA_typing_1$C1, 3, nchar(HLA_typing_1$C1))
HLA_typing_1$C2 <- substr(HLA_typing_1$C2, 3, nchar(HLA_typing_1$C2))
HLA_typing_1$B1 <- substr(HLA_typing_1$B1, 3, nchar(HLA_typing_1$B1))
HLA_typing_1$B2 <- substr(HLA_typing_1$B2, 3, nchar(HLA_typing_1$B2))

# Build GL strings 
gl_strings <- HLA_typing_1 %>% 
  mutate(GL_string = HLA_columns_to_GLstring(., HLA_typing_columns = A1:DPB1_2), .after = patient) %>%
  select(patient, GL_string)

# Select recipient and donor GL strings
recipient <- gl_strings %>% filter(patient == 1) %>% pull(GL_string)
donors <- gl_strings %>% filter(patient %in% 2:5) %>% transmute(donor = patient, donors = GL_string)

# Run HCT summary function on all donors with given recipient in both "Xof8" and "Xof10" matching
results <- donors %>%
  mutate(
    match_8 = map_int(donors, ~ HLA_match_summary_HCT(
      GL_string_recip = recipient, 
      GL_string_donor = .x,
      match_grade = "Xof8")
      ),
    match_10 = map_int(donors, ~ HLA_match_summary_HCT(
      GL_string_recip = recipient,
      GL_string_donor = .x,
      match_grade = "Xof10"
    ))
  )

print(results)
```



::: {.subtitle}
Supplemental table 1 links
:::

[R language](https://www.r-project.org)

[cli package](https://cran.r-project.org/web/packages/cli/index.html)

[dplyr package](https://cran.r-project.org/web/packages/dplyr/index.html)

[glue package](https://cran.r-project.org/web/packages/glue/index.html)

[magrittr package](https://cran.r-project.org/web/packages/magrittr/index.html)

[purrr package](https://cran.r-project.org/web/packages/purrr/index.html)

[rlang package](https://cran.r-project.org/web/packages/rlang/index.html)

[stringr package](https://cran.r-project.org/web/packages/stringr/index.html)

[tibble package](https://cran.r-project.org/web/packages/tibble/index.html)

[tidyr package](https://cran.r-project.org/web/packages/tidyr/index.html)

[tidyselect package](https://cran.r-project.org/web/packages/tidyselect/index.html)

[xml2 package](https://cran.r-project.org/web/packages/xml2/index.html)

[testthat package](https://cran.r-project.org/web/packages/testthat/index.html)
